spring.application.name=api-gateway
server.port=8080
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/      

# User-service route
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Rabka route


spring.cloud.gateway.routes[1].id=restaurant-service
spring.cloud.gateway.routes[1].uri=lb://restaurant-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/restaurant/**

spring.cloud.gateway.routes[2].id=food-service                                                            
spring.cloud.gateway.routes[2].uri=lb://food-service                                               
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/food/**                                            

spring.cloud.gateway.routes[3].id=order-service                                                           
spring.cloud.gateway.routes[3].uri=lb://order-service                                                 
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/order/**  

spring.cloud.gateway.routes[4].id=rabka-service
spring.cloud.gateway.routes[4].uri=http://localhost:8082  
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/**

# JWT secret
jwt.secret=${JWT_SECRET}