spring.application.name=api-gateway
server.port=8080

# User-service route
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Rabka route
spring.cloud.gateway.routes[1].id=rabka-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[2].id=restaurant-service
spring.cloud.gateway.routes[2].uri=http:localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/restaurant/**

# JWT secret
jwt.secret=${JWT_SECRET}