spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/rabka_users
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=update
server.port=8081
