spring.application.name=user-service
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}
spring.cache.type=redis
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=update
server.port=8081
