spring.application.name=restaurant-service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/rabka_restaurant
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/      
